### ISSUE TITLE
Rooted Device. Permission denied, errno = 13

### ISSUE THREAD

**Issue by ashokavarthanan** [amitkhairnar44/root_access#3]
Device is rooted.
real device.

Added **uses-permission** in **AndroidManifest** File.

```
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION"/>
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_SUPERUSER"/>
```

`compileSdkVersion 33`

```
import 'dart:async';
import 'dart:io';
import 'package:permission_handler/permission_handler.dart';
import 'package:root_access/root_access.dart';

Future<void> copyrootfile() async {
    var status = await Permission.storage.status;
    var status2 = await Permission.accessMediaLocation.status;
    var status3 = await Permission.manageExternalStorage.status;
    if (!status.isGranted) {
      await Permission.storage.request();
    }
    if (!status2.isGranted) {
      await Permission.accessMediaLocation.request();
    }
    if (!status3.isGranted) {
      await Permission.manageExternalStorage.request();
    }
    await RootAccess.requestRootAccess;

    var rootFileText = "/data/file.txt";
    final rootFile = File(rootFileText);

    var copyTo = '/storage/emulated/0/documents/file.txt';
    if(rootFile.existsSync()){
        await rootFile.copy(copyTo);
    }
}
```

```
            ElevatedButton(
              onPressed: () async {
                await copyrootfile();
              },
              child: const Text(
                "CopyRootFile",
              ),
            ),
```
When copy data to storage.
it asks permission. But cannot copy.
Note: when using "Root Explorer" app it works fine.

Error :
`Cannot copy file to  OS Error: Permission denied, errno = 13`

```
E/flutter (27371): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot copy file to '/storage/emulated/0/Documents/file.txt', path = '/data/file.txt' (OS Error: Permission denied, errno = 13)
E/flutter (27371): #0      _checkForErrorResponse (dart:io/common.dart:42:9)
E/flutter (27371): #1      _File.copy.<anonymous closure> (dart:io/file_impl.dart:339:7)
E/flutter (27371): <asynchronous suspension>
E/flutter (27371): #2      _MyHomePageState.copyrootfile (package:rootcopy/main.dart:90:7)
E/flutter (27371): <asynchronous suspension>
E/flutter (27371): #3      _MyHomePageState.build.<anonymous closure> (package:rootcopy/main.dart:130:17)
E/flutter (27371): <asynchronous suspension>
```

When copy storage to storage works fine.
```
            ElevatedButton(
              onPressed: () async {
                var copyFrom = '/storage/emulated/0/file.txt';
                var copyTo = '/storage/emulated/0/Documents/file.txt';
                if (File(copyFrom).existsSync()) {
                  await File(copyFrom).copy(copyTo);
                }
              },
              child: const Text(
                "CopyFile",
              ),
            ),
```

Thank you.

**Comment by ashokavarthanan** [comment]
I can't find a solution when using **copy** function to copy file from **data** folder to **storage**. But I was able to find a solution instead.
So i used **root** package instead of **root_access**.
Package Link [root][1].


  [1]: https://pub.dev/packages/root

The succesful code snippet is as follows.

      import 'dart:async';
      import 'dart:io';
      import 'package:permission_handler/permission_handler.dart';
      import 'package:root/root.dart';

      Future<void> copyrootfile() async {
        bool isRooted = await Root.isRooted() ?? false;
        bool isRootAvailable = await Root.isRootAvailable() ?? false;
    
        var status = await Permission.storage.status;
        var status2 = await Permission.accessMediaLocation.status;
        var status3 = await Permission.manageExternalStorage.status;
        if (!status.isGranted) {
          await Permission.storage.request();
        }
        if (!status2.isGranted) {
          await Permission.accessMediaLocation.request();
        }
        if (!status3.isGranted) {
          await Permission.manageExternalStorage.request();
        }
    
        var rootFileText = "/data/file.txt";
        final rootFile = File(rootFileText);
    
        // var copyTo = '/storage/emulated/0/Documents/file.txt';
        var copyToFolder = '/storage/emulated/0/Documents/';
    
        if (rootFile.existsSync()) {
          String copycmd = "cp $rootFileText $copyToFolder";
          if (isRooted && isRootAvailable) {
            await Root.exec(cmd: copycmd);
          }
        }
      }
